---
title: "Introduction"
author: "Oneli (210458262)"
date: "3/27/2023"
output: html_document
---


```{r}
#Initial Data Cleaning And Wrangling
#Reading the data sets
dataset2006 <- read.csv("C:/Users/DELL/Desktop/Coursework/coursework data set/2006.csv")
dataset2007 <- read.csv("C:/Users/DELL/Desktop/Coursework/coursework data set/2007.csv")
datasetairports <- read.csv("C:/Users/DELL/Desktop/Coursework/coursework data set/airports.csv")
datasetcarriers <- read.csv("C:/Users/DELL/Desktop/Coursework/coursework data set/carriers.csv")
datasetplanedata <- read.csv("C:/Users/DELL/Desktop/Coursework/coursework data set/plane-data.csv")

```

```{r}
#Merging the two years of data into one data set
mergeddataset <- rbind(dataset2006, dataset2007)

```

```{r}
#Dropping duplicated rows
mergeddataset <- unique(mergeddataset)
head(mergeddataset)

```

```{r}
#Explore the datasets
dim(dataset2006)
dim(dataset2007)
dim(datasetairports)
dim(datasetcarriers)
dim(datasetplanedata)
dim(mergeddataset)
colnames(mergeddataset)
colnames(datasetairports)
colnames(datasetcarriers)
colnames(datasetplanedata)
str(mergeddataset)
str(datasetairports)
str(datasetcarriers)
str(datasetplanedata)
```

```{r}
write.csv(mergeddataset, file = "C:/Users/DELL/Desktop/Coursework/coursework data set/2006and2007mergeddatasetr.csv", row.names = FALSE)

```






















































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































